name: Windows
on: 
  # push代码时触发workflow
  push:
    branches:
      - main  # 修改成你的主要分支名
      
jobs:
  build:
    name: Build
    # 运行平台， windows-latest目前是windows server 2019 
    # 参考文档 https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md
    runs-on: windows-2019
    strategy:
      # 矩阵配置
      matrix:
        include:
          # 6.0.0 参考 https://mirrors.cloud.tencent.com/qt/online/qtsdkrepository/windows_x86/desktop/qt6_600/
          - qt_ver: 6.0.0
            qt_arch: win64_msvc2019_64
            msvc_arch: x64
            qt_arch_install: msvc2019_64
    env:
      targetName: HelloActions-Qt.exe
    # 步骤
    steps:
      # 进入code
      - name: Change to code directory
        run: pwd
      - name: Change to code directory
        run: dir
      - name: Change to code directory
        run: cd ../code
